services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .././:/var/www/geotest
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - mysql8-service
  php82-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php82-container
    ports:
      - "9001:9000"
    volumes:
      - .././:/var/www/geotest
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3
      MYSQL_PASSWORD: q1w2e3