services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .././:/var/www/geotest
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-container
    ports:
      - "9001:9000"
    volumes:
      - .././:/var/www/geotest
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3
      MYSQL_PASSWORD: q1w2e3