parameters:
  app_title: 'Геотест'
  app_email: 'test@test.test'
  app_username: '<username>'
  app_password: '<password>'
  app_cookie_expire: 2592000
  app_menu_items:
    app_devices:
      title: 'Каталог'
      description: 'Оборудование для полевых<br>исследований грунтов'
    app_about:
      title: 'О компании'
      description: 'О компании'
    app_news:
      title: 'Новости и статьи'
      description: 'Новости и статьи'
    app_order:
      title: 'Оформление заказа'
      description: 'Оформление заказа'
      visible: false
    app_order_save:
      title: 'Оформление заказа'
      description: 'Оформление заказа'
      visible: false